version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql-dev
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heyfy
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-dev
    ports:
      - "6379:6379"

volumes:
  mysql-data: {}
  redis: {}