spring:
  jwt:
    secret: c6f1a8e2b7d4c90e5f3b2a8d7e6c1a5b9d3f8e0c4b6a7d8e9f2a4c1b5d3a7e9c  # 테스트용. 운영은 외부 주입
    access-expiration: 3600000   # 1시간
    refresh-expiration: 604800000 # 7일

  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # dev에서는 호스트의 3307 -> 컨테이너 3306 매핑을 쓴다고 가정
    url: jdbc:mysql://localhost:3306/heyfy?
      useSSL=false&
      allowPublicKeyRetrieval=true&
      serverTimezone=UTC&
      characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      # HikariCP 설정 (필요 시)
      initialization-fail-timeout: 0
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    # Hibernate 6(스프링부트 3)에서는 dialect 자동 감지가 되므로 보통 생략 권장
    # database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create   # 개발용. 운영은 validate 또는 none 권장

shinhan:
  manger-key:  #개인용 키. 각자 바꿔서 사용

springdoc:
  default-produces-media-type: application/json
  api-docs:
    version: OPENAPI_3_1
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  # 콘솔 로그에 traceId(MDC) 노출
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS,Asia/Seoul} %-5level [%X{traceId:-na}] %logger{36} - %msg%n"
  level:
    # 바디까지 상세히 보려면 TRACE (운영에서는 INFO/DEBUG 권장)
    org.zalando.logbook: TRACE
    # 배포서버에서 아래내용 추가
    # org.hibernate.SQL: OFF
    # org.hibernate.type.descriptor.sql.BasicBinder: OFF

logbook:
  # 로깅 제외 경로
  filter:
    exclude:
      - /actuator/**
      - /swagger-ui/**
      - /api-docs/**
      - /error
      - /favicon.ico
  # 헤더/쿼리 파라미터 마스킹(***로 치환)
  obfuscate:
    headers:
      - Authorization
      - Cookie
      - Set-Cookie
    parameters:
      - password
      - accessToken
      - refreshToken
      - token
      - authorization

external:
  apis:
    common:
      manager-key:
    domains:
      edu:
        base-url: https://finopenapi.ssafy.io/ssafy/api/v1/edu  # 교육 관련 API 기본 URL
      member:
        base-url: https://finopenapi.ssafy.io/ssafy/api/v1/member  # 회원 관련 API 기본 URL
  # 외부 API 호출 시 공통 설정
  timeout: 5000  # ms 단위
  retry:
    enabled: true
    max-attempts: 3
    backoff:
      delay: 1000  # ms 단위
      multiplier: 1.5
